### ISSUE TITLE
IOS17 Issue

### ISSUE THREAD

**Issue by shiprec** [raudette/geekweek-7.5_1.3_sneakyairtag#1]
Hello I wanted to ask if you noticed a change in the way IOS17 reports on cloned AirTags?  Specially cloned tags that were implemented using the OpenHaystack protocol?   I was able to track my tags until I updated my phone to IOS17 and now I am not getting any reports.  Any ideas would be greatly appreciated

**Comment by raudette** [comment]
Hello - I was only playing around with Seemoo's Haystack code for a week or two back in 2022 - I haven't played around with it since, so I haven't done any testing with iOS 17.  

That's an interesting issue, but it's not something I'll be looking into - if you do find out why, or how to resolve, let me know, I'd be interested in finding out.

**Comment by shiprec** [comment]
Will do! Thank you for the quick reply.
